"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";

Font.register({
  family: "Inter",
  src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf",
  fontWeight: 400,
});

Font.register({
  family: "Inter",
  src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf",
  fontWeight: 700,
});

const styles = StyleSheet.create({
  page: {
    fontFamily: "Inter",
    padding: 40,
    fontSize: 11,
    color: "#2D3E40",
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 4,
    color: "#2D3E40",
  },
  date: {
    fontSize: 10,
    color: "#6B7F7A",
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 20,
    color: "#FF7A5C",
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    color: "#2D3E40",
  },
  listItem: {
    fontSize: 11,
    lineHeight: 1.8,
    color: "#2D3E40",
    paddingLeft: 12,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#FF7A5C",
    marginRight: 8,
    marginTop: 4,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: "#6B7F7A",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#E8E2D5",
    paddingTop: 8,
  },
});

interface PdfDocumentProps {
  summary: string;
  underperformingCampaigns: string[];
  optimizationSuggestions: string[];
  prioritizedActions: string[];
  date: string;
}

export function PdfDocument({
  summary,
  underperformingCampaigns,
  optimizationSuggestions,
  prioritizedActions,
  date,
}: PdfDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Ad Performance Analysis</Text>
        <Text style={styles.date}>{date}</Text>

        {/* Summary */}
        <Text style={styles.sectionTitle}>Summary</Text>
        <Text style={styles.paragraph}>{summary}</Text>

        {/* Underperforming */}
        {underperformingCampaigns.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Underperforming Campaigns</Text>
            {underperformingCampaigns.map((item, i) => (
              <View key={i} style={styles.listRow}>
                <View style={styles.bullet} />
                <Text style={styles.listItem}>{item}</Text>
              </View>
            ))}
          </>
        )}

        {/* Suggestions */}
        {optimizationSuggestions.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Optimization Suggestions</Text>
            {optimizationSuggestions.map((item, i) => (
              <View key={i} style={styles.listRow}>
                <View style={styles.bullet} />
                <Text style={styles.listItem}>{item}</Text>
              </View>
            ))}
          </>
        )}

        {/* Prioritized Actions */}
        {prioritizedActions.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Prioritized Actions</Text>
            {prioritizedActions.map((item, i) => (
              <View key={i} style={styles.listRow}>
                <Text
                  style={{
                    ...styles.listItem,
                    fontWeight: 700,
                    marginRight: 6,
                    width: 16,
                  }}
                >
                  {i + 1}.
                </Text>
                <Text style={styles.listItem}>{item}</Text>
              </View>
            ))}
          </>
        )}

        <Text style={styles.footer}>
          Generated by Advize -- AI Ads Optimization Advisor
        </Text>
      </Page>
    </Document>
  );
}
